language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - ./vendor/bin/phpunit